### ISSUE TITLE
SpaceAroundControlStructures modifies strings in control blocks

### ISSUE THREAD

**Issue by brettp** [phpfmt/php.tools#89]
Given a block of code like this

```php
if (true) {
	$label = "{$foo}{$bar}";
}
```

SpaceAroundControlStructures modifies it to this:

```php
if (true) {
	$label = "{$foo}
{$bar}";
}
```

**Comment by Shaked** [comment]
@brettp I am very sorry for this bug, I will fix it ASAP.

**Comment by Shaked** [comment]
@brettp Would you be able to share the config\entire pass stack that you are using?

**Comment by brettp** [comment]
Thanks for the quick reply! Here's how I'm calling it: 

```
visibility_order=1
smart_linebreak_after_curly=1
yoda=1
passes="
	AlignGroupDoubleArrow,AlignTypehint,AlignPHPCode,AlignDoubleSlashComments,

	ReindentAndAlignObjOps,ReindentSwitchBlocks,

	DocBlockToComment,PrettyPrintDocBlocks,

	RemoveUseLeadingSlash,DoubleToSingleQuote,ReturnNull,ShortArray,
	PSR2EmptyFunction,UpgradeToPreg,ConvertOpenTagWithEcho,AutoPreincrement,

	MergeNamespaceWithOpenTag,SpaceBetweenMethods,PSR2LnAfterNamespace,OrganizeClass,MergeElseIf,

	SpaceAroundControlStructures
"
no-backup=1
ignore=vendor,fmt.php,refactor.php

[test]
no-backup=1
ignore=vendor,fmt.php,refactor.php
```

**Comment by Shaked** [comment]
Thanks, I am on it!

**Comment by ccirello** [comment]
@Shaked this will be useful:

https://github.com/phpfmt/php.tools/blob/e2efeb7a3217cb4cd3a40c177ca2f6a86b51db8d/src/Additionals/ReindentSwitchBlocks.php

**Comment by Shaked** [comment]
Fixed in 02f6f86, the fix will be available in the next release.

**Comment by brettp** [comment]
:clap: Fantastic! Thanks for the insanely prompt attention to this!

**Comment by ccirello** [comment]
It is not fixed, @Shaked - check this: https://github.com/phpfmt/php.tools/commit/dfb7e1b5a6c425cbff674bffcf1224549c3097b1

I really suggest you use this:
https://github.com/phpfmt/php.tools/blob/e2efeb7a3217cb4cd3a40c177ca2f6a86b51db8d/src/Additionals/ReindentSwitchBlocks.php#L23-L37

**Comment by Shaked** [comment]
@ccirello added
